/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations, Box } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Object3D } from "three";
import { easing } from "maath";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/motorcyclist.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Armature|mixamo.com|Layer0"].play();
  }, [actions["Armature|mixamo.com|Layer0"]]);

  const [dummy] = useState(() => new Object3D());
  const bones = nodes.Mesh.skeleton.bones;

  useFrame((state, dt) => {
    dummy.lookAt(state.pointer.x, state.pointer.y, 1);
    if (Math.abs(state.pointer.x) < 0.95 && Math.abs(state.pointer.y) < 0.95) {
      easing.dampQ(bones[5].quaternion, dummy.quaternion, 0, dt);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig6Hips} />
          <group name="Ch20">
            <skinnedMesh
              castShadow
              name="Mesh"
              geometry={nodes.Mesh.geometry}
              material={materials.Ch20_body}
              skeleton={nodes.Mesh.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={materials.helmet}
              skeleton={nodes.Mesh_1.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh_2"
              geometry={nodes.Mesh_2.geometry}
              material={materials.visor}
              skeleton={nodes.Mesh_2.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh_3"
              geometry={nodes.Mesh_3.geometry}
              material={materials.shoes}
              skeleton={nodes.Mesh_3.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh_4"
              geometry={nodes.Mesh_4.geometry}
              material={materials.gloves}
              skeleton={nodes.Mesh_4.skeleton}
            />
          </group>
          <skinnedMesh
            castShadow
            name="SnowBall001"
            geometry={nodes.SnowBall001.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.SnowBall001.skeleton}
          />
          <skinnedMesh
            castShadow
            name="SnowBall002"
            geometry={nodes.SnowBall002.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.SnowBall002.skeleton}
          />
          <skinnedMesh
            castShadow
            name="SnowBall003"
            geometry={nodes.SnowBall003.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.SnowBall003.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/motorcyclist.gltf");
